project:
  type: default
  render:
    - main.qmd
    - README.qmd

title: |
  Joint learning of RKHS and kernel sum-of-squares functions:\
  a representer theorem and its convex dual
subtitle: ""
author:
  - name: Louis Allain
    corresponding: true
    email: louis.allain@safrangroup.com
    url: 
    orcid: 0009-0005-1009-0198
    affiliations:
      - name: Safran AI Research, Magny-Les-Hameaux, France
        url: https://www.safran-group.com/group/innovation/safran-tech
      - name: Univ Rennes, Ensai, CNRS, CREST - UMR 9194, F-35000 Rennes, France
        url: https://crest.science/
  - name: Sébastien Da Veiga
    email: sebastien.da-veiga@ensai.fr 
    url: https://sites.google.com/view/sebastien-da-veiga/home
    orcid: 0009-0004-1637-7942
    affiliations:
      - name: Univ Rennes, Ensai, CNRS, CREST - UMR 9194, F-35000 Rennes, France
        url: https://crest.science/
date: last-modified
date-modified: last-modified
abstract: >+
  Kernel sum-of-squares (kSoS) models represent a non-negative function as a quadratic form in an reproducing kernel Hilbert space (RKHS), guaranteeing non-negativity everywhere. It has emerged as a promising kernel approach to model non-negative phenomena, leveraging a representer theorem that makes the problem tractable. 
  This result only holds for kSoS functions, and with the same RKHS. However, real-world problems may require to learn general-valued functions _jointly_ with kSoS functions, and may also benefit from different kernels for each kSoS function for better predictive accuracy.
  In this work, we thus consider such wider class of statistical learning problems, where we are interested in jointly learning $p$ real valued functions and $q$ non-negative functions defined on different RKHS. Building on representer theorems from traditional kernel methods and kSoS, we introduce a new generalized representer theorem for that learning problem. The induced finite-dimensional problem is a semi-definite program (SDP), easily solvable using off-the-shelf solvers. To scale better than SDP solvers, we also establish a convex dual formulation, which writes as an optimization problem with only $\mathcal{O}(n)$ variables and no positive semi-definite constraints. Finally, for completeness and to highlight the potential of the kSoS framework, we derive the explicit dual formulations for three kSoS problems previously introduced in the literature and provide two new problems leveraging the generalized representer theorem. All our experiments are reproducible with our accompanying Python code.
keywords: [kernel sum-of-squares, statistical learning]
bibliography: references.bib
github-user: Lui5ito
repo: "ksos-computo-submission"
status: submitted
license: CC-BY-4.0
citation:
  type: article-journal
  container-title: "Computo"
  issn: "2824-7795"
  doi: "10.5072/computo.0000" # placeholder DOI (10.5072 is the official DOI test prefix), replace once assigned
crossref:
  cnj-title: Assumption
  cnj-prefix: Assumption
format:
  computo-html: default
  computo-pdf: default
jupyter: python3
